import { Inter } from "next/font/google";
import "../../app/globals.css";

import Footer from "../components/Footer";
import Header from "../components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Platinum Driveline México",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header />
      <main className={inter.className}>{children}</main>
      <Footer />
    </html>
  );
}
